CLASSES = ["mug", 
            "egg",
           "onion",
           "plate",
            "banana", 
            "apple", 
            "tomato",
            "knife", 
            "bowl",
            "pot",
             "bottle",
             "spoon", 
              "orange", 
              "porcelain",
              "fork",
              "cup"
              "pan"]